import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Howl, Howler } from "howler";

export default function Home() {
  Howler.volume(0.5);
  const cw = new Howl({
    src: ["/audio/coma-white-dv.mp3"],
  });
  const toggleCW = () => {
    console.log("here");
    if (cw.playing()) {
      cw.pause();
    } else {
      cw.play();
    }
  };

  // Shoot the laser!
  // sound.play("laser");
  return (
    <div className={styles.container}>
      <Head>
        <title>WebAmp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>WebAmp</h1>
        <p className={styles.description}>Choose a song to play:</p>
        <p>
          <button onClick={toggleCW}>Coma White</button>
          <button>Lateralus</button>
        </p>

        <div>
          <p>This is a placeholder!</p>
        </div>
      </main>

      <footer className={styles.footer}>Powered by Aliens!</footer>
    </div>
  );
}
